name = "deepseek-r1-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
RATE_LIMIT = "10"
RATE_LIMIT_WINDOW = "60000"

[env.production.vars]
RATE_LIMIT = "20"
RATE_LIMIT_WINDOW = "60000"

[env.staging.vars]
RATE_LIMIT = "5"
RATE_LIMIT_WINDOW = "60000"

# Use 'wrangler secret put API_KEY' to set your OpenAI API key
